import { Check, ExternalLink, RefreshCw, Sparkles, Trash2, Undo2 } from "lucide-react";
import { useRef, useState } from "react";
import type { Action, Conversation, Feed, Snapshot } from "../shared/schema";
import { OpmlDialog } from "./OpmlDialog";
import { Dialog } from "./Dialog";
import { RunStatus } from "./AiPanel";
import { agentName } from "./format";

type Props = { removedFeeds: Feed[]; snapshot: Snapshot; folderId: string | null; act: (action: Action) => Promise<void>; perform: (action: Action) => void; openConversation: (conversation: Conversation) => void };

export function LibraryDialogs({ removedFeeds, snapshot, folderId, act, perform, openConversation }: Props) {
  const feedDialog = useRef<HTMLDialogElement>(null);
  const folderDialog = useRef<HTMLDialogElement>(null);
  const activityDialog = useRef<HTMLDialogElement>(null);
  const [feedError, setFeedError] = useState<string | null>(null);
  const [folderError, setFolderError] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const [saving, setSaving] = useState(false);
  const { state, connections } = snapshot;
  const readyAgent = connections.find((item) => item.agent === "codex" && item.status === "ready")?.agent ?? connections.find((item) => item.status === "ready")?.agent ?? null;
  return <>
    <OpmlDialog report={snapshot.opmlImport} preview={snapshot.opmlPreview} hasFeeds={state.feeds.length > 0} act={act} perform={perform} organize={snapshot.organize} agent={readyAgent} />
    <Dialog id="feed-dialog" title="フィードを追加" dialogRef={feedDialog} onClose={() => setFeedError(null)}><p className="dialog-description">読みたいサイトのRSS / Atom URLを登録します。</p><form onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setAdding(true); setFeedError(null); void act({ type: "feed.add", url: String(data.get("url") ?? ""), folderId: String(data.get("folder") ?? "") || null }).then(() => { form.reset(); feedDialog.current?.close(); }).catch((error: unknown) => setFeedError(error instanceof Error ? error.message : "追加できませんでした。")).finally(() => setAdding(false)); }}><label htmlFor="feed-url">フィードURL</label><input id="feed-url" name="url" type="url" placeholder="https://example.com/feed.xml" required autoComplete="off" aria-invalid={!!feedError} aria-describedby={feedError ? "feed-error" : undefined} /><label htmlFor="feed-folder">フォルダ</label><select id="feed-folder" name="folder"><option value="">フォルダなし</option>{state.folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select>{feedError ? <p className="form-error" id="feed-error" role="alert">{feedError}</p> : null}<div className="dialog-actions"><button className="secondary-button" type="button" commandfor="feed-dialog" command="close">キャンセル</button><button type="submit" className="primary-button" disabled={adding}>{adding ? "取得しています…" : "フィードを追加"}</button></div></form></Dialog>
    <Dialog id="folder-dialog" title={folderId ? "フォルダ名を変更" : "フォルダを作成"} dialogRef={folderDialog} onClose={() => setFolderError(null)}><form key={folderId ?? "new"} onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setSaving(true); setFolderError(null); void act({ type: "folder.save", id: folderId, name: String(data.get("name") ?? "") }).then(() => { form.reset(); folderDialog.current?.close(); }).catch((error: unknown) => setFolderError(error instanceof Error ? error.message : "保存できませんでした。")).finally(() => setSaving(false)); }}><label htmlFor="folder-name">フォルダ名</label><input id="folder-name" name="name" defaultValue={state.folders.find((folder) => folder.id === folderId)?.name ?? ""} placeholder="テクノロジー、デザイン…" required maxLength={60} aria-invalid={!!folderError} />{folderError ? <p className="form-error" role="alert">{folderError}</p> : null}<div className="dialog-actions"><button className="secondary-button" type="button" commandfor="folder-dialog" command="close">キャンセル</button><button type="submit" className="primary-button" disabled={saving}>{saving ? "保存中…" : "保存"}</button></div></form></Dialog>
    <Dialog id="connections-dialog" title="エージェント接続"><p className="dialog-description">MacにあるCLIのログインを使います。<br />Reedar専用のAPIキーは必要ありません。</p><div className="connections">{connections.map((connection) => <div key={connection.agent} className="connection-item"><div className="connection-title"><strong>{agentName[connection.agent]}</strong><span className={`connection-state connection-${connection.status}`}>{connection.status === "ready" ? <><Check size={12} />接続済み</> : connection.status === "checking" ? "確認中" : connection.status === "authentication" ? "ログインが必要" : connection.status === "unavailable" ? "未インストール" : connection.status === "unsupported" ? "連携準備中" : "接続エラー"}</span></div><p>{connection.detail}</p>{connection.status === "authentication" ? <div className="login-command">ターミナルで <code>{connection.agent === "claude" ? "claude auth login" : "codex login"}</code></div> : null}</div>)}</div><p className="dialog-footnote">記事の閲覧と会話に限定して接続します。ファイル操作、外部ツール、追加の権限要求は許可しません。</p><div className="dialog-actions"><button className="secondary-button" onClick={() => perform({ type: "connections.refresh" })}><RefreshCw size={13} />接続を再確認</button></div></Dialog>
    <Dialog id="activity-dialog" title="AIの会話" dialogRef={activityDialog}><div className="activity-list">{[...state.conversations].reverse().map((conversation) => { const last = conversation.messages.at(-1); return <button key={conversation.id} className="activity-row" onClick={() => { openConversation(conversation); activityDialog.current?.close(); }}><div><span>{agentName[conversation.agent]}</span>{last?.role === "assistant" ? <RunStatus state={last.state} /> : null}</div><strong>{conversation.source.title}</strong><p>{last?.text.slice(0, 120) || (last?.role === "assistant" ? last.state.status === "failed" ? last.state.error : last.state.status === "waiting" ? last.state.reason : last.state.status === "cancelled" ? "回答を中止しました" : last.state.status === "completed" ? "完了しました" : "回答を待っています" : "会話を開始できます")}</p><ExternalLink size={13} /></button>; })}{!state.conversations.length ? <p className="dialog-description">記事を開いて「AIと読む」を選ぶと、ここに会話が残ります。</p> : null}</div></Dialog>
    <Dialog id="organize-dialog" title="フィードの整理"><p className="dialog-description">フォルダの移動やフィードの削除ができます。削除したフィードは更新されなくなり、一覧から非表示になります。記事・スター・会話は保持され、ここから復元できます。進行中のAI回答は停止します。</p><div className="organize-list">{state.feeds.map((feed) => <div className="organize-row" key={feed.id}><label><span>{feed.title}</span><select aria-label={`${feed.title}のフォルダ`} value={feed.folderId ?? ""} onChange={(event) => perform({ type: "feed.move", id: feed.id, folderId: event.target.value || null })}><option value="">フォルダなし</option>{state.folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><button className="icon-button remove-feed" aria-label={`${feed.title}を削除`} title="フィードを削除" onClick={() => perform({ type: "feed.remove", id: feed.id })}><Trash2 size={15} /></button></div>)}</div>{!state.feeds.length ? <p className="dialog-description">登録中のフィードはありません。</p> : null}<OrganizeSection snapshot={snapshot} readyAgent={readyAgent} act={act} perform={perform} />{removedFeeds.length ? <details className="removed-feeds"><summary>削除済みのフィード（{removedFeeds.length}）</summary><div className="organize-list">{removedFeeds.map((feed) => <div key={feed.id} className="restore-row"><span>{feed.title}</span><button className="text-button" aria-label={`${feed.title}を復元`} onClick={() => perform({ type: "feed.restore", id: feed.id })}><Undo2 size={13} />復元</button></div>)}</div></details> : null}</Dialog>
  </>;
}

function OrganizeSection({ snapshot, readyAgent, act, perform }: { snapshot: Snapshot; readyAgent: Snapshot["connections"][number]["agent"] | null; act: (action: Action) => Promise<void>; perform: (action: Action) => void }) {
  const job = snapshot.organize;
  const [deselected, setDeselected] = useState<Set<string>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const chosen = job?.plan?.moves.filter((move) => !deselected.has(move.feedId)) ?? [];
  return <div className="organize-ai">
    <h3>AIの整理案</h3>
    {readyAgent ? <div className="dialog-actions"><button className="secondary-button" type="button" disabled={!snapshot.state.feeds.length || job?.status === "running"} onClick={() => { setDeselected(new Set()); setError(null); void act({ type: "organize.propose", agent: readyAgent, scope: "library" }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "整理案を依頼できませんでした。")); }}><Sparkles size={13} />AIに整理案を作成</button></div>
      : <p className="dialog-description">AI整理案にはCodexまたはClaudeの接続が必要です。「エージェント接続」から接続してください。</p>}
    {job?.status === "running" ? <div className="dialog-actions"><p className="dialog-description">整理案を生成しています…</p><button className="secondary-button" type="button" onClick={() => perform({ type: "organize.cancel" })}>中止</button></div> : null}
    {job?.status === "failed" ? <p className="form-error" role="alert">{job.detail ?? "整理案を作成できませんでした。"}</p> : null}
    {error ? <p className="form-error" role="alert">{error}</p> : null}
    {job?.scope === "library" && job.status === "completed" ? (job.plan?.moves.length ? <>
      <ul className="opml-preview-list">
        {job.plan.moves.map((move) => <li key={move.feedId}><label><input type="checkbox" checked={!deselected.has(move.feedId)} onChange={(event) => { const next = new Set(deselected); if (event.target.checked) next.delete(move.feedId); else next.add(move.feedId); setDeselected(next); }} aria-label={`${move.title}の移動を選択`} /><span className="opml-entry-body"><strong>{move.title}</strong><span className="opml-entry-detail">移動先: {move.folderName}{move.newFolder ? "（新規フォルダ）" : ""}</span></span></label></li>)}
      </ul>
      <div className="dialog-actions"><button className="primary-button" type="button" disabled={!chosen.length} onClick={() => { setError(null); void act({ type: "organize.apply", moves: chosen.map((move) => ({ feedId: move.feedId, folderName: move.folderName })) }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "適用できませんでした。")); }}>選択した{chosen.length}件を適用</button><button className="secondary-button" type="button" onClick={() => perform({ type: "organize.clear" })}>破棄</button></div>
    </> : <div className="dialog-actions"><p className="dialog-description">移動の提案はありませんでした。</p><button className="secondary-button" type="button" onClick={() => perform({ type: "organize.clear" })}>閉じる</button></div>) : null}
  </div>;
}
